optimizer:
  name: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 1e-6

lr_scheduler:
  name: 'cos_anneal_restart_reduce'
  T_0: 70
  T_mult: 2
  lr_mult: 0.9
  eta_min: !!float 8e-5

max_norm: 0.3
ema_decay: 0.99

path:
  wv3_train_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/wv3/training_wv3/train_wv3.h5"
  wv3_val_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5"

  gf2_train_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5"
  gf2_val_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"

  qb_train_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5"
  qb_val_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"

  cave_x4_train_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5"
  cave_x4_val_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/test_cave(with_up)x4.h5"

  cave_x8_train_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/x8/train_cave(with_up)x8_rgb_16.h5"
  cave_x8_val_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/test_harvard(with_up)x8_rgb.h5"

  msrs_base_dir: "/Data3/cao/ZiHanCao/datasets/MSRS"
  llvip_base_dir: "/Data3/cao/ZiHanCao/datasets/LLVIP/data"  # the mask is generated by using Ground-DINO-SAM project
  tno_base_dir: "/Data3/cao/ZiHanCao/datasets/TNO"
  roadscene_base_dir: "/Data3/cao/ZiHanCao/datasets/RoadSceneFusion"
  roadscene_tno_joint_base_dir: "/Data3/cao/ZiHanCao/datasets/RoadScene_and_TNO"
  med_harvard_base_dir: "/Data3/cao/ZiHanCao/datasets/MedHarvard"

network_configs:
  GF_chans: 60
  embed_dim: 60
  depths: 
    - 6
    - 6
  num_heads: 
    - 6
    - 6
  window_size: 8
  kernel_num: 
    - 1
    - 1
    - 1
  mlp_ratio: 2.0
  inference: false
  
logger_config:
  base_path: ./log_file/
  name: MGDN
  file_mode: w
